apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/bootstrap:jenkins-a7289d82015e23a671f000b477db7db0d3011047
          name: container-image
